apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  namespace: osable
  labels:
    application: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      application: url-shortener
  template:
    metadata:
      labels:
        application: url-shortener
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: url-shortener
          image: registry.osable.net/osable/url-shortener:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: url-shortener-mysql-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-shortener-mysql-credentials
                  key: password
          ports:
            - containerPort: 10101