---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: core-webhook-url
  namespace: osable
spec:
  encryptedData:
    url: AgBXHz87z2v72Xji4NdzVFlO2cVon+WuKtQsEp4omqoZkyYNifj9zX4y5jvyH6NZIQfT62vqAk4yNoRkNv6uoYWwi+Bo0Cf2LLul7mwtBsMjmbYpKmi6X4X/1jpA5GbEWNn4F/xI5lKQSHoCol9TiazoE40qRZnT7gMSw8mIrvP+KeF0KrC2D3SoXXVHV1lGjvzdRXWP6FpMN2VXgnnOdztyInOw3DHkBpUG4Z2RH7QcndDkStPK7ANK5d4Qn/gj//1sUDTNccf9d4zRkKTpr3TvYC+Qm96QhwYDUcfvkUMt4oKvMaoYXWL7b/OYYn6kZv3XU6kowyHWGoaf/pxqKf7E7+7YWR3fkJu9VkKwBjQgkAFO7Tp1BetXJLq/V4u2vxsr/6HZGhz5qlinOMbj238t+5CColjc/sYqxSL4K3waxicfTCrLMBCL2DEZtwG7qcpQKlkGuYnqgWdSEa7G1hzTP5Fj+ufVzOgGfDgyGqkHsV52hiDV2nPxEF9ymJd8rZbGqplGBFgY+Nvc/hw8KB0ih06jlCt4NzA/9WIpb7z3YQHIqDn92mruTn3Aik74WD9hoObi3QFiAqoYQOWGNUq0KF2Yn7hwCSAMVHdF5eBX7ye/Of42ENiFPNbP0hfScEblkC20fnjaO+ntZ4I44AjtyYNxQAwmhjlB5YT2y2uyFvc5sBpXQeY+kP/SKFQ3tDHMH1vSHNUjdhSc1w3OoEBf5Zt3t530Lf3QCQ8JPRmygVDNIGjqVfIOtjWIEK6GhMWYhExScY2Acwh3ftVI2Ybf6kjPuvF4JWCvf5u4s1/PbUGOp1l80g7cQLAbVaPkTOgzOMqXHj8+xltijPN5kFRNZMOTRYwBLFg=
  template:
    metadata:
      creationTimestamp: null
      name: core-webhook-url
      namespace: osable
