---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gateway-redis-credentials
  namespace: osable
spec:
  encryptedData:
    password: AgBfriwRhW7nh+mF7//f1bjh4a0ON619764FZppN2KP8rnX10tufFfAwLUmIQL7Fmu8dxRxX7gL0SWekETW0XdUoKHHJ2538MALgb7bVD3XCQ3/n/Kp3tIHd/P4kR+Eox4fQQkUiWuNnRaqgIflXAA/n542qNgKlB26+YAzuzEL2y6HOieGVoKYfOWQe2IvoXVMyHLzLUg5M93DvTpAbkKCHDGqBfXrqkBAD/Grt2RjUMQPmmavmKAde+uMlKsYMVK59IRPZ7vcwVv59G1WITJCKmvFyH1rqF82gPDGXWOs1EsIAPa0VEj2e1J+JngKpPw2tlJa+deN4Jw2FuLP4NAqHJYf0kP2vUZ+OXptlajMv+ZtN7s4UkWvIByjBhmdLio5CDvs/WGk0pxW7P9QSS/Ztrn3NMKPbfmCo4KUNgOBlEYLzLTXFMSOkSwG4wx3VBYTlWwf+MnKUzzq/cmwLc1TqRvMWqVCKfRKANkchVNqA7/xY8qnGGhFxKcXn41vyplBDpwBnT2FTuRaUpUgsYqfQ8LqhAVELbThdSScbcReXDpg1EnrE6VeTcllTEnd8LYcmf4Cp1xnNq8H/gBuAX8ZM6yBLWHwWHsCWPVygqhqF0AIl4/GN+MtPRHNiX6JvMCb40HVH6KkagWqc1QojSHn0AxpaIGfBipzmaR16ksxfQGawcEhTu3vzlV+FyqJvPUq+VmfvVXG1CFOHxvRfb8DiJDn4OQ==
  template:
    metadata:
      creationTimestamp: null
      name: gateway-redis-credentials
      namespace: osable
    type: Opaque
