apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: osable
spec:
  interval: 15m
  timeout: 5m
  releaseName: mysql
  chartRef:
    kind: OCIRepository
    name: mysql
  valuesFrom:
    - kind: ConfigMap
      name: mysql-helm-chart-value-overrides
      valuesKey: values.yaml