apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysql
  namespace: osable
spec:
  chart:
    spec:
      chart: mysql
      version: 12.2.2
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: mysql
  valuesFrom:
    - kind: ConfigMap
      name: mysql-helm-chart-value-overrides
      valuesKey: values.yaml