apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: mysql
  namespace: osable
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/mysql
  ref:
    semver: ">12.2.0"