apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: docker-registry-pvc
    namespace: osable
spec:
	volumeName: docker-registry-pv
	storageClassName: local-path
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi