apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery
  namespace: osable
  labels:
    application: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      application: discovery
  template:
    metadata:
      labels:
        application: discovery
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: discovery
          image: registry.osable.net/osable/discovery:latest
          ports:
            - containerPort: 8761