apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docker-config-prod
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/docker-config
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system