apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: le-issuer
 namespace: cert-manager
spec:
 acme:
   email: webmaster@osable.net
   # We use the staging server here for testing to avoid rate limits
   # server: https://acme-staging-v02.api.letsencrypt.org/directory
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: le-issuer-account-key
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik