apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/production/cert-manager/config
  dependsOn:
    - name: "cert-manager"
    - name: "sealed-secrets"
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system