apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: url-shortener
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: "docker-config"
  path: ./apps/production/url-shortener
  prune: true 
  timeout: 2m 
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: url-shortener
      namespace: osable