apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: discovery
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: "docker-config"
  path: ./apps/production/discovery
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: discovery
      namespace: osable
