apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 15m
  path: ./apps/production/monitoring
  prune: true 
  timeout: 2m 
  sourceRef:
    kind: GitRepository
    name: flux-system