apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: config--mysql
  namespace: flux-system
spec:
  interval: 15m
  path: ./apps/production/mysql/config
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system