apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docker-config
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: "docker-registry"
  path: ./infrastructure/production/docker-config
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: regcred
      namespace: osable
