apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mysql
  namespace: flux-system
spec:
  interval: 15m
  dependsOn:
    - name: "config--mysql"
  path: ./apps/production/mysql/helm
  prune: true 
  timeout: 2m 
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: mysql
      namespace: osable