apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb--metallb-system-prod
  namespace: flux-system
spec:
  interval: 15m
  path: ./infrastructure/base/metallb/helm
  prune: true
  timeout: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system