apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: osable
spec:
  chart:
    spec:
      chart: redis
      version: 19.6.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: redis
  valuesFrom:
    - kind: ConfigMap
      name: redis-helm-chart-value-overrides
      valuesKey: values.yaml