- name: K3s installation playbook
  hosts: localhost
  tasks:
    - name: Create path for k3s install config
      file:
        path: /etc/rancher/k3s
        state: directory

    - name: Copy K3s installation config
      copy:
        src: ./k3s-config.yaml
        dest: /etc/rancher/k3s/config.yaml

    - name: Install & Start K3s
      command: curl -sfL https://get.k3s.io | sh -

    - name: Set KUBECONFIG
      command: export KUBECONFIG=/etc/rancher/k3s/k3s.yaml