apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 1.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: monitoring-helm-chart-value-overrides
      valuesKey: values.yaml